//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheEntityStoreManagementProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExchangePermit
    {
        public int permit_id { get; set; }
        public Nullable<int> store_id { get; set; }
        public string permit_number { get; set; }
        public Nullable<System.DateTime> permit_date { get; set; }
        public Nullable<int> supplier_id { get; set; }
        public Nullable<int> item_id { get; set; }
        public Nullable<int> quantity { get; set; }
    
        public virtual item item { get; set; }
        public virtual store store { get; set; }
        public virtual supplier supplier { get; set; }
    }
}
